version: '3.7'
services:
  api:
    container_name: api
    build:
      context: ./ulut_parser_api
      args:
        - RUN_DB_MIGRATIONS_ARG=yes
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ulut_parser_api:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    env_file:
      - web-variables.env
volumes:
  postgres_data:
  

