version: '3.7'
services:

  api:
    container_name: api
    build:
      context: ./ulut_parser_api
      dockerfile: Dockerfile
      args:
        - RUN_DB_MIGRATIONS_ARG=yes
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ulut_parser_api:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgre
    image: postgres:12.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery:
    container_name: celery
    build:
      context: ./ulut_parser_api
    restart: "no"
    env_file:
      - .env
    links:
      - redis
    command: celery -A main worker -l info
    volumes:
      - ./ulut_parser_api:/code
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:5
    command: redis-server
    ports:
      - 6379:6379

volumes:
  postgres_data:
