# Generated by Django 3.0 on 2020-11-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('account_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код аккаунта')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя')),
                ('avatar_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Аватар url')),
                ('biography', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='AccountPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код поста')),
                ('caption', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание поста')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_posts', to='instagram_app.Account', verbose_name='Автор поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.CharField(max_length=300, verbose_name='Медиа URL')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_medias', to='instagram_app.AccountPost', verbose_name='ID поста')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
            },
        ),
    ]
