name: Publish Docker image
on:
  push:
    branches: [master]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: Teststep
            run: ls
          -   name: Build and push docker image
              uses: docker/build-push-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  dockerfile: ./ulut_parser_api/Dockerfile
                  repository: 444555444666/docker_repository
                  tag_with_ref: true
